general:
  project_name: HAR

dataset:
  name: wisdm
  class_names: [Jogging,Stationary,Stairs,Walking]
  training_path:


pre_processing:
  segment_len: 24
  segment_step: 24
  preprocessing: True

model:
  model_type: {name : ign}
  input_shape: [24,3,1]
  model_path: ../../models/ign/ST_pretrainedmodel_public_dataset/WISDM/ign_wl_24/ign_wl_24.h5
  
quantization:
  quantize: False
  evaluate: False
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: float
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  c_project_path: ../../getting_started
  serie: STM32U5
  IDE: GCC
  verbosity: 1
  version: 8.1.0
  optimization: balanced
  footprints_on_target: B-U585I-IOT02A
  path_to_stm32ai: C:/STMicroelectronics/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/8.1.0/Utilities/windows/stm32ai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.1.0/STM32CubeIDE/stm32cubeidec.exe

mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}